### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by NagabhushanSN95** [rubenvillegas/icml2017hierchvid#1]
Hi,
Can you provide pretrained models for your networks?

**Comment by rubenvillegas** [comment]
Sorry, I don't have them with me anymore. You should be able to get comparable or better results than the paper by running the code in this repo. The LSTM architecture in this repo has a slight improvement from the one in the paper which should get you even longer video sequences. (~5 minutes of reasonable frame generation in the Human 3.6M dataset).

**Comment by NagabhushanSN95** [comment]
Okay thanks!
